@startuml Temperature API - Context Diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Temperature API - Контейнер

System_Boundary(api_system, "Temperature API") {
    System(api, "Temperature API", "", "Go")
}

System_Ext(app, "Приложение умного дома")

' Связи
Rel(app, api, "Запрос температуры по локации/комнате", "REST/JSON")

@enduml