@startuml Temperature API - class diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml

class Temperature {
	+Value: float64
	+Unit: string
	+Timestamp: Time
	+Location: string
	+Status: string
	+SensorID: string
	+SensorType: string
	+Description: string
}

class TemperatureService {
	+Temperature GetTemperatureByLocation()  
	+Temperature GetTemperatureByID()  
}

@enduml