@startuml Основное приложение - Context Diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Тёплый дом - Компоненты (Монолит)

Person(user, "Пользователь", "Сотрудник или клиент")

System_Boundary(api, ""){
    System(temperatureService, "Temperature Service", "")
    System(dbService, "database Service", "")
    System(handlers, "Handlers", "")
}

System(postgres, "PostgreSQL", "База данных датчиков")
System(temperature_api, "Temperature API", "Микросервис датчиков температуры", "Go")

' Связи
Rel(handlers, temperatureService, "CRUD запросы", "Read/Write")
Rel(user, handlers, "CRUD запросы", "Read/Write")
Rel(dbService, postgres, "CRUD запросы", "Read/Write")
Rel(handlers, dbService, "CRUD запросы", "Read/Write")
Rel(temperatureService, temperature_api, "CRUD запросы", "Read/Write")

@enduml