@startuml

hide circle
skinparam linetype ortho

entity "Sensor" {
  * SensorId : NUMBER
  --
	Value    :   float64 
	Unit      :  string 
	Timestamp :  Timestamp
	Location   : string    
	Status     : string
	SensorType : string    
	Description: string    
}

entity "User" {
  * UserId : NUMBER
  --
  username : VARCHAR
  email : VARCHAR
  password : VARCHAR
}

entity "SensorTelemetry" {
  * SensorId : NUMBER
  --
    Value    :   string 
    Unit      :  string 
    Timestamp :  Timestamp
    Location   : string    
	Status     : string
	SensorType : string    
}

entity "Scenario" {
  * ScenarioId : NUMBER
  --
  userId : NUMBER
  name : VARCHAR
  enabled: BOOL
}

entity "Condition" {
  * ConditionId : NUMBER
  --
    ScenarioId: NUMBER
    SensorId: VARCHAR,
    propertyName: VARCHAR,
    operator: VARCHAR,
    value: VARCHAR
}

entity "Commands" {
  * CommandId : NUMBER
  --
    ScenarioId: NUMBER
    SensorId: VARCHAR,
    command: VARCHAR,
    payload: json
}

User ||--o{ Sensor
User ||--o{ Scenario
Scenario ||--o{ Condition
Scenario ||--o{ Commands
Sensor ||--o{ SensorTelemetry

@enduml