@startuml
' Настройки диаграммы
hide circle
skinparam linetype ortho

' Сущности для контекста "Телеметрия датчиков"
entity "User" as user {
  + userid: number <<generated>>
  --
  * серийный_номер: string
  * модель: string
  статус: string
}

' Сущности для контекста "Телеметрия датчиков"
entity "Sensor" as sensor {
  + sensorId: number <<generated>>
  --
    Value    :   float64 
    Unit      :  string 
    Timestamp :  Timestamp
    Location   : string    
    Status     : string
    SensorType : string    
}

entity "SensorTelemetry" as reading {
  + sensorId: number <<generated>>
  --
    Value    :   float64 
    Unit      :  string 
    Timestamp :  Timestamp
    Location   : string    
	  SensorType : string    
}

' Сущности для контекста "Управление датчиками"
entity "Конфигурация" as config {
  + id: number <<generated>>
  --
  * параметр: string
  * значение: string
  * дата_изменения: timestamp
}

' Сущности для контекста "Датчики температуры"
entity "Температурный_Датчик" as temp_sensor {
  + sensorId: number <<FK>>
  --
  * мин_температура: float
  * макс_температура: float
  * единица_измерения: string
}

' Связи между сущностями
user ||-o{ sensor

sensor ||-o{ reading : "имеет"
sensor ||-o{ config : "настроен"
sensor ||--|| temp_sensor : "расширяет"

@enduml