@startuml Telemetry - components diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title API Телеметрии - компоненты

Person(user, "Пользователь", "(WEB/Mobile/App)")

Boundary(bound, "API Адаптеры к умным устройствам", "логическая группа API"){
    System(temperature, "Temperature API", "Система отопления")
    System(lighting, "Lighting API", "Система управления освещением")
    System(video, "Video API", "Система видеонаблюдения стриминг")
    System(gates, "Gates API", "Система управления дверьми")
    System(others, "Others API", "И другие еще не известные")
}

Container(telemetry, "Телеметрия") {
    Component(handlers, "HTTP Handlers", "REST", "Приём входящих HTTP-запросов")
    Component(mqtt_handler, "AMQP Handler", "Подписка на топики устройств")
    Component(telemetry_service, "Telemetry service", "Сервис получения и агрегации данных")
    Component(db_component, "Database component", "Репозиторий")
}

ContainerDb(telemetry_db, "База данных телеметрии", "SQL/Timeseries")

' Связи

Rel(bound, mqtt_handler, "Новые данные телеметрии")

Rel(user, handlers,"Получение телеметрии усройства/устройств", "JSON/HTTPS")
Rel(handlers, telemetry_service,"")
Rel(telemetry_service, db_component, "Read")

Rel(mqtt_handler, db_component, "Write")

Rel(db_component, telemetry_db, "")

@enduml